name: LKS Auto Judge

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x judge-check.sh

      - name: Run judge script
        run: ./judge-check.sh
